version: '3'

services:
  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      # - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.enable=true"
      - "traefik.port=9000"
    ports:
      - '0:80'

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.backend=portainer"
      # - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:portainer.docker.localhost"
      - "traefik.enable=true"
      - "traefik.port=9000"
    ports:
      - '0:9000'


volumes:
  portainer_data:
